[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
miniserve = { path = "../miniserve" }
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
